# Generated by Django 5.0.6 on 2026-04-01 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (must be positive)', max_digits=12)),
                ('record_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Type of transaction: income or expense', max_length=10)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment Returns'), ('business', 'Business Income'), ('rental', 'Rental Income'), ('other_income', 'Other Income'), ('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('rent', 'Rent/Mortgage'), ('healthcare', 'Healthcare'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('education', 'Education'), ('travel', 'Travel'), ('insurance', 'Insurance'), ('maintenance', 'Maintenance'), ('taxes', 'Taxes'), ('other_expense', 'Other Expense')], help_text='Category for classification', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of the transaction')),
                ('description', models.CharField(blank=True, help_text='Brief description of the transaction', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or details')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'db_table': 'financial_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
